version: '3.8'

services:
  nginx:
    build: ./docker/nginx
    container_name: vps-nginx
    networks:
      - web
    volumes:
      - "./www:/usr/share/nginx/html"
      - "./docker/nginx/default.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/sites-available:/etc/nginx/sites-available"
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - "php"

  php:
    build: ./docker/php
    container_name: vps-php
    networks:
      - web
    volumes:
      - "./www:/home"
    depends_on:
      - "db"

  composer:
    build: ./docker/composer
    entrypoint: /home/composer/docker/composer/entrypoint.sh
    container_name: vps-composer
    networks:
      - web
    volumes:
      - "./:/home/composer"
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name : vps-db
    # hostname: mysql_host
    networks:
      - web
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASS}
      MYSQL_DATABASE: ${SQL_DATABASE}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_USER_PASS}
      # MYSQL_ROOT_HOST: '%'
    volumes:
      - "./docker/db:/var/lib/mysql"

networks:
  web:
    name: web