# Building from official php image
# FROM php:8.1-fpm-alpine AS php
FROM composer:2.3.5 AS composer

# COPY --from=composer:2.3.5 /usr/bin/composer /usr/local/bin/composer

# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# CMD [ "php-fpm" ]